export const era_1950__events__disasters = `
## 1950S EVENTS - DISASTERS
- Norco Louisiana Refinery Explosion (1955-05-16): 0 fatalities (evacuated in time) but 350+ homes destroyed. Cause: A hydrocarbon leak at the Shell refinery ignited, causing a boiling liquid expanding vapor explosion (BLEVE) that devastated the surrounding town.
- Great Smog of London (1952-12-05): 4,000–12,000 fatalities over 5 days (estimates vary). Cause: Anticyclone weather trapped coal smoke and vehicle exhaust under a temperature inversion. Sulfur dioxide and particulates reached lethal concentrations. Visibility dropped to 1 meter.
- 1950 Nebraska Floods (South Platte River) (1950-06-04): 0 direct fatalities (15,000 displaced, massive crop destruction). Cause: Heavy rains combined with snowmelt caused the South Platte River to overflow, inundating towns and farmland across western Nebraska.
- Windscale Fire (1957-10-10): 0 immediate fatalities (est. 240 eventual cancer deaths from radiation release). Cause: A routine "annealing" procedure (heating the graphite moderator to release stored Wigner energy) overheated the uranium fuel, igniting the graphite core. Operators hesitated to use water because they feared a hydrogen explosion.
- 1956 Grand Canyon Mid-Air Collision (1956-06-30): 128 fatalities (all aboard both aircraft). Cause: TWA Lockheed Super Constellation and United Airlines DC-7 collided over the Grand Canyon while both were flying in uncontrolled airspace under visual flight rules. Neither pilot saw the other. This disaster directly led to the creation of the modern ATC system and radar coverage.
- Munich Air Disaster (British European Airways Flight 609) (1958-02-06): 23 fatalities (including 8 Manchester United footballers — the "Busby Babes"). Cause: The BEA Airspeed Ambassador aircraft attempted takeoff in slush on the runway. Slush slowed the aircraft below rotation speed. The pilot attempted two failed takeoffs before the third, fatal attempt. The wing hit a house and the plane caught fire.
- 1959 Bradfield Canal / Big Delta Flood (Alaska) (1959-01-15): 0 fatalities (massive infrastructure damage). Cause: Ice jam on the Tanana River caused flooding that destroyed roads and bridges.
- Cyclone Connie (Queensland Flooding) (1959-01-18): 0 fatalities (extreme rainfall, massive flooding). Cause: Tropical Cyclone Connie produced record rainfall over Queensland, causing widespread flooding across the Fitzroy and Burnett river catchments.
`;
