export const era_1950__science__tech = `
## 1950S SCIENCE - TECH
- Tech Transfer Target: Polio Vaccine Acceleration (Salk Inactivated) (Optimal Year: 1951): Jonas Salk's inactivated poliovirus vaccine (IPV) was proven effective in the 1954 field trial and licensed April 12, 1955. Polio paralyzed ~15,000 Americans per year in the early 1950s. Accelerating the trial by even 2 years prevents ~30,000 cases of paralysis. Target: Jonas Salk at the University of Pittsburgh.
- Tech Transfer Target: Transistor Radio Commercialization (Optimal Year: 1951): The Regency TR-1 (October 1954) was the first transistor radio, built with Texas Instruments transistors. It proved transistors could replace vacuum tubes in consumer products. Accelerating this by 2-3 years jumpstarts the entire consumer electronics revolution. Target: Texas Instruments semiconductor division (Gordon Teal, Pat Haggerty).
- Tech Transfer Target: FORTRAN High-Level Programming Language (Optimal Year: 1953): FORTRAN (FORmula TRANslation) was the first high-level programming language, developed by John Backus at IBM (1954-1957). It demonstrated that compiled code could approach hand-coded assembly in performance, transforming software development from an art into engineering. Target: John Backus at IBM Research, New York.
- Tech Transfer Target: Laser (Light Amplification by Stimulated Emission of Radiation) (Optimal Year: 1956): The laser was invented by Theodore Maiman at Hughes Research Labs on May 16, 1960, building on the theoretical work of Charles Townes and Arthur Schawlow (1958 paper). Lasers enabled fiber optics, barcode scanners, CD players, laser eye surgery, and precision manufacturing. Target: Charles Townes at Columbia University.
- Tech Transfer Target: Weather Satellite / Remote Earth Observation (Optimal Year: 1957): TIROS-1 (Television Infrared Observation Satellite), launched April 1, 1960, was the first weather satellite. It proved that satellite imagery could track cloud patterns and storm systems, transforming meteorology from ground-based guesswork to global observation. Target: NASA Goddard Space Flight Center / RCA Astro Electronics.
- Tech Transfer Target: Implantable Cardiac Pacemaker (Optimal Year: 1957): The first fully implantable pacemaker was developed by Wilson Greatbatch and Dr. William Chardack, implanted in a human patient in 1960. It used a mercury battery and delivered electrical pulses to regulate heartbeat. Pacemakers have since saved millions of lives. Target: Wilson Greatbatch (independent inventor, Buffalo NY).
- Tech Transfer Target: Touch-Tone (DTMF) Telephone Signaling (Optimal Year: 1958): Dual-tone multi-frequency (DTMF) signaling replaced rotary dial phones with push-button keypads. Invented at Bell Labs, first demonstrated in 1963, and rolled out commercially in the late 1960s. DTMF enabled automated phone systems, voicemail, and eventually interactive voice response. Target: Bell Labs switching engineering group.
- Tech Transfer Target: Microwave Oven Consumer Design (Optimal Year: 1958): Percy Spencer at Raytheon discovered microwave heating in 1945 (a chocolate bar melted in his pocket near a radar magnetron). The first commercial Radarange (1947) was the size of a refrigerator and cost $5,000. The first countertop home model (Amana RR-1, 1967) cost $495 and transformed cooking. Target: Raytheon appliance division / Amana subsidiary.
- Tech Transfer Target: CNC Machine Tool Standardization (G-Code) (Optimal Year: 1955): While NC machining was invented at MIT in 1952, the standard programming language (G-code, formally RS274) took over a decade to emerge. Standardizing it earlier would have accelerated CNC adoption across manufacturing worldwide. Target: MIT Servomechanisms Lab / Aircraft Industries Association (AIA).
- Tech Transfer Target: Color TV Manufacturing Cost Reduction (Optimal Year: 1957): Color TVs existed since 1954 (RCA CT-100, $1,000) but cost 3-5x more than B&W sets and had reliability problems. By 1965, RCA's improvements brought prices to $350-500 and color TV sales exploded. Accelerating this cost curve by 3-4 years means tens of millions of households get color TV sooner. Target: RCA Consumer Electronics division (David Sarnoff, CEO).
`;
