export const era_1950__culture__sports = `
## 1950S CULTURE - SPORTS
- NFL Championship — "The Greatest Game Ever Played" (1958): Baltimore Colts def. New York Giants 23-17 OT (Colts -3.5), First NFL game to go to overtime. Johnny Unitas engineers a legendary drive. Alan Ameche scores the winning TD. This game single-handedly popularized professional football on national TV and set the stage for the AFL-NFL merger and the Super Bowl era.
- NFL Championship (1956): New York Giants def. Chicago Bears 47-7 (Bears slight favorites), Giants destroy the Bears. Frank Gifford runs for a TD, catches a TD, and throws a TD pass. The Giants' most dominant championship performance.
- NFL Championship (1950): Cleveland Browns def. Los Angeles Rams 30-28 (Rams -2), Browns' first NFL championship after moving from the AAFC. Otto Engineers a comeback. Lou Groza kicks the winning FG with 28 seconds left. Proved AAFC teams could compete in the NFL.
- World Series — Don Larsen's Perfect Game (1956): New York Yankees def. Brooklyn Dodgers 4-3 (Yankees -160), Don Larsen throws the only perfect game in World Series history (Game 5). Yogi Berra leaps into his arms. The Yankees win the series in 7 games. The only no-hitter in postseason history until 2010.
- World Series — Willie Mays' Catch (1954): New York Giants def. Cleveland Indians 4-0 (Indians -160 (won 111 games)), Willie Mays makes "The Catch" — an over-the-shoulder basket catch in deep center field at the Polo Grounds in Game 1. Indians won 111 regular season games (AL record at the time) but get swept.
- World Series (1951): New York Yankees def. New York Giants 4-2 (Yankees -200), The "Shot Heard Round the World" — Bobby Thomson's walk-off HR wins the NL pennant for the Giants over the Dodgers. Yankees then beat the Giants in the Series. Joe DiMaggio's final season.
- World Series — Brooklyn Dodgers Finally Win (1955): Brooklyn Dodgers def. New York Yankees 4-3 (Yankees -180), Brooklyn Dodgers win their FIRST World Series after 5 previous losses to the Yankees. Johnny Podres pitches a 2-0 shutout in Game 7. Sandy Amoros makes a game-saving catch in left field. The borough of Brooklyn erupts.
- World Series — Milwaukee Braves (1957): Milwaukee Braves def. New York Yankees 4-3 (Yankees -150), Hank Aaron hits .393 with 3 HRs. Lew Burdette wins 3 games including a Game 7 shutout on 2 days rest. The Braves' only championship in Milwaukee.
- Heavyweight Championship (1952): Rocky Marciano def. Jersey Joe Walcott KO 13th round (Walcott -8.5), Marciano wins the heavyweight title with a devastating right hand that knocks Walcott unconscious against the ropes. Marciano would retire undefeated at 49-0 — the only heavyweight champ to do so.
- Heavyweight Championship (1954): Rocky Marciano def. Ezzard Charles KO 8th round (Marciano -300), Marciano retains title in rematch. Charles had pushed Marciano to the brink in their first fight (split decision). Marciano knocks him out in the rematch.
- World Middleweight Championship (1957): Sugar Ray Robinson def. Gene Fullmer KO 5th round (Fullmer slight favorite), Robinson reclaims the middleweight title with a perfectly timed left hook. At 36 years old, Robinson becomes a 5-time world champion — a record that still stands. Many consider Robinson the greatest pound-for-pound fighter ever.
`;
