export const era_1950__science__medical = `
## 1950S SCIENCE - MEDICAL
- Polio Vaccine (Salk IPV) Field Trial Acceleration (Optimal Year: 1951): The 1954 Salk vaccine field trial was the largest public health experiment in history: 1.8 million children. The vaccine was proven effective and licensed April 12, 1955. The 1952 polio epidemic was the worst in US history (58,000 cases, 3,145 deaths, 21,269 paralyzed).
- Thalidomide Teratogenicity Prevention (Optimal Year: 1959): Thalidomide was marketed as a mild sedative and anti-nausea drug for pregnant women starting in 1957 (West Germany). It caused severe birth defects (phocomelia — limb malformations) in ~10,000 babies worldwide. FDA reviewer Frances Kelsey blocked its US approval, preventing thousands of American cases.
- Open Heart Surgery / Cardiopulmonary Bypass (Optimal Year: 1950): The first successful open-heart surgery using a heart-lung machine was performed by John Gibbon in 1953 (closure of an atrial septal defect). C. Walton Lillehei at the University of Minnesota pioneered cross-circulation (1954) and then the DeWall-Lillehei bubble oxygenator (1955), making open-heart surgery practical.
- Oral Contraceptive Pill Development (Optimal Year: 1952): The first oral contraceptive (Enovid) was developed by Gregory Pincus and John Rock, funded by Margaret Sanger and Katharine McCormick. FDA approved it in 1960. It transformed women's autonomy, family planning, and demographics worldwide.
- Kidney Transplant / Immunosuppression (Optimal Year: 1957): The first successful kidney transplant between identical twins was performed by Joseph Murray in 1954 (Nobel Prize 1990). The breakthrough for unrelated donors came with azathioprine (an immunosuppressant) in 1962, enabling transplants between non-identical individuals.
- Measles Vaccine (Optimal Year: 1959): Measles killed ~500 children per year in the US and caused encephalitis in thousands more before the vaccine. John Enders' lab developed the live attenuated measles vaccine (Edmonston strain), licensed in 1963. Maurice Hilleman later improved it into the MMR combination vaccine.
- CPR (Cardiopulmonary Resuscitation) Standardization (Optimal Year: 1957): Modern CPR (closed-chest compression + mouth-to-mouth ventilation) was developed and demonstrated by William Kouwenhoven, James Jude, and Guy Knickerbocker at Johns Hopkins in 1960. The American Heart Association formally endorsed CPR in 1963. Before CPR, cardiac arrest outside a hospital was almost universally fatal.
- Antipsychotic Medication (Chlorpromazine/Thorazine) (Optimal Year: 1950): Chlorpromazine (Thorazine) was the first effective antipsychotic drug, transforming the treatment of schizophrenia and other severe mental illnesses. Developed in France (Rhône-Poulenc, 1950) and introduced to psychiatry by Henri Laborit and Pierre Deniker. FDA approved in 1954. It emptied mental asylums.
- Oral Polio Vaccine (Sabin OPV) (Optimal Year: 1954): Albert Sabin's oral polio vaccine (OPV) used live attenuated virus administered on a sugar cube. Unlike Salk's injected vaccine (IPV), OPV provided intestinal immunity (stopping transmission) and was cheap enough for mass global vaccination campaigns. Licensed in the US in 1962, it became the backbone of the global polio eradication effort.
`;
