export const era_1960__culture__sports = `
## 1960S CULTURE - SPORTS
- NFL Championship (1962): Green Bay Packers def. New York Giants 16-7 (Packers -9), Vince Lombardi's Packers win their 2nd straight championship at Yankee Stadium in brutal cold. Jerry Kramer and Fuzzy Thurston lead the famous "Packers Sweep." The beginning of the Packers dynasty.
- NFL Championship — "The Ice Bowl" (1967): Green Bay Packers def. Dallas Cowboys 21-17 (Packers -7), Played in -13°F wind chill at Lambeau Field. Bart Starr scores the winning TD on a QB sneak behind Kramer with 16 seconds left. Arguably the greatest NFL game ever played. The Packers go on to win Super Bowl II.
- Super Bowl I (AFL-NFL World Championship) (1967): Green Bay Packers def. Kansas City Chiefs 35-10 (Packers -14), The first Super Bowl. Lombardi's Packers dominate. Max McGee catches 7 passes for 138 yards and 2 TDs despite being hungover — he had partied all night because he didn't expect to play. The game was not a sellout.
- Super Bowl III — "The Guarantee" (1969): New York Jets def. Baltimore Colts 16-7 (Colts -18), Joe Namath guarantees victory and delivers. The AFL's first Super Bowl win legitimized the merger. One of the greatest upsets in sports history. The Colts were 18-point favorites.
- World Series — Mazeroski's Walk-Off (1960): Pittsburgh Pirates def. New York Yankees 4-3 (Yankees -200), Bill Mazeroski hits a walk-off home run in Game 7 — the only Game 7 walk-off HR in World Series history. Yankees outscored the Pirates 55-27 in the series but LOST. A bizarre, thrilling upset.
- World Series (1961): New York Yankees def. Cincinnati Reds 4-1 (Yankees -250), Roger Maris hits 61 home runs during the regular season, breaking Babe Ruth's single-season record (with an asterisk due to the expanded 162-game schedule). Whitey Ford pitches 2 shutouts.
- World Series (1966): Baltimore Orioles def. Los Angeles Dodgers 4-0 (Dodgers -160), Orioles sweep the defending champion Dodgers. Frank Robinson wins the Triple Crown during the regular season (.316, 49 HR, 122 RBI). Jim Palmer, at 20 years old, outpitches Sandy Koufax in Game 2. Koufax's final season.
- World Series — "Impossible Dream" (1967): St. Louis Cardinals def. Boston Red Sox 4-3 (Cardinals -150), The Red Sox go from 9th place in 1966 to the pennant — the "Impossible Dream." But Bob Gibson dominates with 3 complete game victories (1.00 ERA, 26 Ks). Carl Yastrzemski wins the Triple Crown but loses the Series.
- World Series — "The Year of the Pitcher" (1968): Detroit Tigers def. St. Louis Cardinals 4-3 (Cardinals -130), Bob Gibson posts a 1.12 ERA during the regular season (lowest live-ball era ERA). Denny McLain wins 31 games (last 30-game winner). Mickey Lolich wins 3 games including Game 7 on 2 days rest. The "Year of the Pitcher" led directly to the lowering of the mound in 1969.
- Heavyweight Championship — "The Upset" (1964): Muhammad Ali (Cassius Clay) def. Sonny Liston TKO 7th round (Liston 7-1 favorite), 22-year-old Cassius Clay shocks the world by beating the fearsome Sonny Liston. Clay dances, jabs, and refuses to be cornered. After the fight, he announces his conversion to Islam and changes his name to Muhammad Ali. The most transformative sporting event of the 1960s.
- Heavyweight Championship — "The Phantom Punch" (1965): Muhammad Ali def. Sonny Liston KO 1st round (1:44) (Ali -4), Ali knocks out Liston with a punch so fast that many ringside didn't see it. The "phantom punch" controversy persists to this day. The iconic photo of Ali standing over Liston is one of the most famous sports photos ever taken.
- Heavyweight Championship (1967): Muhammad Ali def. Zora Folley KO 7th round (Ali -8), Ali's last fight before his 3-year exile for refusing the Vietnam draft. He was 29-0 and in his prime. He would not fight again until 1970. The Supreme Court overturned his conviction in 1971.
- NBA Finals (1962): Boston Celtics def. Los Angeles Lakers 4-3 (Celtics -200), Bill Russell grabs 40 rebounds in Game 7. Sam Jones hits the game-winning shot with 2 seconds left. Celtics win their 4th straight title. The beginning of the greatest dynasty in NBA history (8 straight championships, 11 in 13 years).
- NBA Finals (1969): Boston Celtics def. Los Angeles Lakers 4-3 (Lakers -180), Bill Russell's final game. John Havlicek steals the ball in the Eastern Conference Finals ("Havlicek stole the ball!"). Celtics win Game 7 in LA despite being underdogs. Russell retires with 11 championships in 13 years. Don Nelson's shot bounces over the rim and in.
- NBA Regular Season — Wilt Chamberlain Scores 100 (1962): Philadelphia Warriors def. New York Knicks 169-147 (N/A (regular season)), Wilt Chamberlain scores 100 points in a single game — the most unbreakable record in NBA history. He shot 36-of-63 from the field and 28-of-32 from the free throw line (career 51% FT shooter). The game was played in Hershey, PA — no TV cameras, only a few hundred fans.
- Stanley Cup Finals (1960): Montreal Canadiens def. Toronto Maple Leafs 4-0 (Canadiens -200), Canadiens win their 5th straight Stanley Cup — still the longest consecutive championship streak in NHL history. Maurice "Rocket" Richard scores the Cup-winning goal in his final season.
- Super Bowl II (1968): Green Bay Packers def. Oakland Raiders 33-14 (Packers -14), Lombardi's final game as Packers coach. Bart Starr MVP. Packers dominate the AFL champions for the 2nd straight year.
`;
