export const era_1960__events__disasters = `
## 1960S EVENTS - DISASTERS
- 1960 Valdivia Earthquake (1960-04-12): 1,000–6,000 fatalities (estimates vary widely). Cause: The most powerful earthquake ever recorded (Mw 9.5). Subduction zone rupture lasting 10 minutes. Generated a tsunami that crossed the Pacific, killing 61 in Hilo, Hawaii and ~140 in Japan.
- 1961 Ndola United Nations DC-6 Crash (Dag Hammarskjöld) (1961-09-18): 16 fatalities (including UN Secretary-General Dag Hammarskjöld). Cause: The UN DC-6 crashed on approach to Ndola airport. Official cause: controlled flight into terrain (CFIT) due to pilot error in poor visibility. Conspiracy theories persist but the official finding is CFIT.
- Aberfan Coal Tip Disaster (1966-10-21): 144 fatalities (116 children, 28 adults — an entire primary school buried). Cause: Coal spoil tip (Tip 7) on a hillside above the village became saturated after heavy rain and collapsed onto Pantglas Junior School and nearby houses. The National Coal Board had been warned about the tip's instability years earlier.
- 1964 Anchorage Good Friday Earthquake (1964-07-12): 131 fatalities (mostly from tsunami). Cause: Second most powerful earthquake ever recorded (Mw 9.2). Lasted 4 minutes 38 seconds. Triggered landslides in Anchorage and a tsunami that devastated Valdez, Seward, Kodiak, and coastal towns down to California.
- Apollo 1 Fire (1967-01-27): 3 fatalities (astronauts Gus Grissom, Ed White, Roger Chaffee). Cause: Fire erupted in the pure-oxygen atmosphere of the Apollo 1 command module during a plugs-out test. The 100% oxygen environment at 16.7 psi made everything flammable. A spark from a chafed wire ignited the nylon harnesses, and the inward-opening hatch could not be opened against the pressure.
- Silver Bridge Collapse (Point Pleasant, WV) (1967-12-15): 46 fatalities. Cause: A single eyebar chain link in the suspension bridge developed a hidden fatigue crack (0.1 inch deep) that fractured under load during rush-hour traffic. The bridge was fracture-critical: one link fails, the whole bridge falls. No redundancy.
- Vajont Dam Disaster (1963-10-09): 1,917–2,500 fatalities (entire town of Longarone destroyed). Cause: A massive landslide (260 million cubic meters) from Monte Toc collapsed into the Vajont reservoir, displacing water that overtopped the dam in a 250-meter mega-tsunami. The dam itself survived — the wave went over it. Engineers had observed the mountain creeping for years but continued filling the reservoir.
- Torrey Canyon Oil Spill (1967-03-18): 0 human fatalities (one of the worst environmental disasters in UK history — 25,000+ seabirds killed, 180+ miles of coastline contaminated). Cause: Supertanker Torrey Canyon struck Pollard's Rock on the Seven Stones Reef while taking a shortcut to save time. The captain had ordered a course change to pass west of the Scilly Isles but the ship was too large for the maneuver at that speed.
`;
