export const era_1970__economics__finance = `
## 1970S ECONOMICS - FINANCE
- 1971-08-15 (Currency): End of Bretton Woods / Nixon Shock. Direction: UP. Peak: Gold: $35 → $183/oz by 1974  US dollar delinked from gold. Gold rises 5x in 3 years. This is the foundational trade of the decade.
- 1973-01-11 to 1974-12-06 (Market Crash): 1973-74 Bear Market. Direction: DOWN. Peak: DJIA: 1,051 (Jan 1973) Trough: DJIA: 577 (Dec 1974) Oil embargo + Watergate + inflation. Worst bear market since Great Depression. -45% peak to trough.
- 1973-10-17 to 1974-03-18 (Commodity): OPEC Oil Embargo. Direction: UP. Peak: Oil: $3 → $12/barrel  Oil quadruples in 6 months. Gas lines in the US. Speed limits reduced to 55 mph. Backlash creates Japanese auto import boom.
- 1979-01 to 1980-04 (Commodity): 1979 Oil Crisis (Iranian Revolution). Direction: UP. Peak: Oil: $13 → $39.50/barrel (Apr 1980)  Second oil shock. Lines at gas stations return. "Odd/even" license plate rationing in some states.
- 1979-07 to 1980-01-21 (Commodity): Gold Mania. Direction: UP. Peak: Gold: $300 → $850/oz (Jan 21, 1980)  Soviet invasion of Afghanistan + Iran hostage crisis + double-digit inflation. Hunt brothers attempt to corner silver market simultaneously.
- 1979 to 1980-03-27 (Commodity): Hunt Brothers Silver Corner (Silver Thursday). Direction: UP. Peak: Silver: $6 → $49.45/oz (Jan 18, 1980)  Nelson Bunker Hunt and William Herbert Hunt try to corner the global silver market. COMEX changes rules to break the corner on "Silver Thursday" (Mar 27, 1980).
- 1970-10-01 (IPO): Walmart Goes Public. Direction: UP. Peak: IPO: $16.50/share (split-adjusted: ~$0.005)  38 stores at IPO. By 1990: 1,500+ stores. Stock splits 2-for-1 eleven times between 1971 and 1999. $1,000 invested at IPO = $12M+ by 2024.
- 1978-06-06 (Real Estate): California Proposition 13 Passes. Direction: UP.   Prop 13 caps property taxes at 1% of assessed value and limits annual increases to 2%. This makes California real estate uniquely attractive. Buy BEFORE it passes.
- 1970-06-21 (Market Crash): Penn Central Bankruptcy. Direction: DOWN. Peak: PC stock: $86 (1968) → $0 Trough: Bankrupt — June 21, 1970 Largest US bankruptcy at the time. Congress passes the Emergency Loan Guarantee Act (1970), effectively creating a bailout template reused for Lockheed (1971) and Chrysler (1979).
- 1971-12-18 (Currency): Smithsonian Agreement — Dollar Devaluation. Direction: UP. Peak: Gold: official $38/oz (market $100+ by 1973)  Nixon called it "the most significant monetary agreement in history." It lasts 14 months before collapsing into the modern floating-rate era.
- 1973-12 to 1975-02 (Market Crash): UK Secondary Banking Crisis. Direction: DOWN. Peak: UK property equities down ~70% peak-to-trough Trough: Lifeboat rescue props banks at fraction of book Roughly 30 secondary banks fail. Property and banking excesses of the Heath-barber boom unwind violently. Direct precursor to the 1976 sterling crisis.
- 1974-06-26 (Currency): Herstatt Bank Failure (Settlement Risk). Direction: DOWN. Peak: DM/USD whipsaw: $1 = 3.25 DM (Jan) → 2.36 (May) Trough: Bank closed during NY trading hours Creates "Herstatt risk" — the danger that one party pays in one timezone but the counterparty defaults before reciprocating. Drives creation of CLS Bank decades later.
- 1975-07-18 (Commodity): Brazilian Black Frost — Coffee Spike. Direction: UP. Peak: Coffee: $0.45 → $3.39/lb (1977)  Largest frost in Brazil's coffee belt in recorded history. US supermarket coffee prices triple. The 1977 peak stands as the all-time high for more than 20 years.
- 1975-04 to 1975-11 (Real Estate): New York City Fiscal Crisis. Direction: DOWN. Peak: NYC municipal bonds trade at ~50 cents on the dollar Trough: Citicorp and NY banks refuse to roll NYC short-term debt Ford's "DROP DEAD" NYT headline (Oct 29, 1975) symbolizes federal refusal to bail out NYC. The city avoids default by hours. SoHo brownstones bought in 1977 = generational wealth.
`;
