export const era_1970__science__medical = `
## 1970S SCIENCE - MEDICAL
- H. Pylori & Peptic Ulcers (Optimal Year: 1979): Bacterium causes 90% of duodenal ulcers and 80% of gastric ulcers. Treatable with a 2-week antibiotic course instead of lifelong antacids or surgery.
- HIV/AIDS Early Warning & Response (Optimal Year: 1978): HIV-1 retrovirus causes AIDS. Transmission: blood, sexual contact, mother-to-child. Prevention: condoms, clean needles, blood screening. First clusters appeared in 1981 but the virus likely circulated since the 1960s.
- Reye's Syndrome / Aspirin Warning (Optimal Year: 1977): Reye's Syndrome: rapid liver failure and brain swelling in children given aspirin during viral infections (flu, chickenpox). Mortality rate ~30%. Survivors often have permanent brain damage.
- Childhood Lead Exposure Reduction (Optimal Year: 1974): Lead is a neurotoxin. Childhood exposure (primarily from leaded gasoline and lead paint) causes permanent IQ reduction, behavioral disorders, and developmental delays. The effects are dose-dependent with no safe threshold.
- Fetal Alcohol Syndrome Awareness (Optimal Year: 1975): Alcohol consumption during pregnancy causes Fetal Alcohol Spectrum Disorders (FASD): facial abnormalities, growth deficiency, CNS damage, intellectual disability. 100% preventable.
- Hepatitis B Vaccine Acceleration (Optimal Year: 1977): Hepatitis B virus causes chronic liver disease and hepatocellular carcinoma. A plasma-derived vaccine was developed in 1981; a recombinant vaccine followed in 1986.
- Oral Rehydration Therapy (ORT) for Cholera & Diarrheal Disease (Optimal Year: 1970): A simple solution of clean water, glucose, and salts (sodium, potassium, citrate) reverses the fatal dehydration that kills ~5 million children annually from diarrheal disease. The Lancet called ORT "potentially the most important medical advance of the 20th century." It costs pennies per dose and requires no hospital.
- Smallpox Eradication — Surveillance-Containment Strategy (Optimal Year: 1970): Smallpox killed ~300 million people in the 20th century before its eradication in 1980 — the only human disease ever eradicated. The breakthrough was abandoning mass-vaccination-everyone in favor of surveillance-containment (ring vaccination): find outbreaks fast, isolate them, and vaccinate every contact in a ring around each case.
- Statins (HMG-CoA Reductase Inhibitors) for Cardiovascular Disease (Optimal Year: 1976): Statins lower LDL cholesterol by inhibiting HMG-CoA reductase, the rate-limiting enzyme in cholesterol synthesis. Lovastatin (Mevacor), the first commercial statin, was approved by the FDA in September 1987. Statins reduce major cardiovascular events by ~25-35% and have become the most prescribed drug class in history.
- ACE Inhibitors (Captopril) for Hypertension & Heart Failure (Optimal Year: 1974): ACE inhibitors block angiotensin-converting enzyme, lowering blood pressure and reducing afterload on the failing heart. Captopril (Capoten), the first oral ACE inhibitor, was approved by the FDA in April 1981. The class became first-line therapy for hypertension, heart failure, and diabetic nephropathy.
`;
