export const era_1980__science__tech = `
## 1980S SCIENCE - TECH
- Public Telephones & Early Mobile: Touch-tone phones replace rotary by mid-80s. First mobile phones (1983: Motorola DynaTAC, $3,995, "the brick").
- Navigation Without GPS: Still paper maps. First consumer GPS (Magellan NAV 1000) launches in 1989 at $3,000 — but it's handheld, not in cars.
- Banking & ATMs: ATM networks (Cirrus, Plus) launch mid-80s. Debit cards appear around 1984-85 but are not widely used.
- Computers & Internet: Home computers: Apple II (1977), Commodore 64 (1982), IBM PC (1981). Macintosh (1984). BBS (bulletin board systems) exist — modem dial-up to individual servers. No web until 1991.
- Music & Media: CDs launch 1982, gain traction slowly. Cassette remains dominant portable format. Walkman (Sony, 1979) is ubiquitous by 1983.
- Tech Transfer Target: Polymerase Chain Reaction (PCR) DNA Amplification (Optimal Year: 1983): PCR amplifies a specific DNA sequence by many orders of magnitude (doubling each cycle) using thermal cycling with sequence-specific primers and a heat-stable DNA polymerase. Kary Mullis conceived it at Cetus Corporation in 1983; the use of Taq polymerase (from Thermus aquaticus) in 1986 made it practical. PCR underpins DNA sequencing, genetic diagnostics, forensic DNA fingerprinting, and molecular biology research. Mullis won the 1993 Nobel Prize. Target: Kary Mullis at Cetus Corporation, Emeryville CA.
- Tech Transfer Target: Gallium Nitride Blue LED (Bright LED Lighting) (Optimal Year: 1989): Bright blue LEDs based on gallium nitride (GaN) enabled, for the first time, white LED lighting (blue diode + yellow phosphor). Shuji Nakamura at Nichia Chemical Industries demonstrated the first high-brightness GaN blue LED in 1993-94, after decades of failed work on zinc selenide. LEDs use ~85% less energy than incandescent bulbs and last 25x longer. Nakamura, Akasaki, and Amano shared the 2014 Nobel Prize. Target: Shuji Nakamura at Nichia Chemical Industries (Tokushima, Japan).
`;
