export const era_1980__science__medical = `
## 1980S SCIENCE - MEDICAL
- AZT (Zidovudine) Early Development for HIV/AIDS (Optimal Year: 1984): Azidothymidine (AZT) was the first antiretroviral drug effective against HIV. It inhibits reverse transcriptase, the enzyme HIV uses to copy itself into host DNA. Developed by Burroughs Wellcome with the NIH (Samuel Broder, Hiroaki Mitsuya), it was approved by the FDA on March 19, 1987 in record time (25 months).
- Aspirin for Acute Myocardial Infarction (Heart Attack) (Optimal Year: 1987): A 162-300mg aspirin given during an acute myocardial infarction reduces mortality by ~23% and prevents re-infarction. It costs pennies, is available everywhere, and was definitively proven by the ISIS-2 trial (1988). Yet adoption was spotty for years despite the evidence.
- Haemophilus influenzae type b (Hib) Vaccine (Optimal Year: 1985): Haemophilus influenzae type b was the leading cause of bacterial meningitis in children under 5 in the US (~20,000 cases/year before vaccination). Mortality ~5%, and ~30% of survivors had permanent neurologic damage (deafness, seizures, intellectual disability). Conjugate vaccine development eliminated this disease wherever it was adopted.
- Vitamin A Supplementation to Prevent Childhood Blindness & Mortality (Optimal Year: 1983): Vitamin A deficiency causes xerophthalmia (the leading cause of preventable childhood blindness) and dramatically increases all-cause child mortality. Alfred Sommer (Johns Hopkins) proved in 1983 that even mild xerophthalmia was associated with a 2-3x increased risk of death. Twice-yearly vitamin A capsules reduce childhood mortality by 23-34%.
- Zinc Supplementation for Acute Diarrhea in Children (Optimal Year: 1985): Zinc supplementation during acute diarrhea reduces episode duration (~25%), severity, and subsequent episodes over the following months. Combined with oral rehydration salts, it reduces diarrhea mortality by ~23%. Zinc-ORS is now WHO standard of care for pediatric diarrhea.
- Hospital Hand Hygiene Protocols to Reduce Nosocomial Infections (Optimal Year: 1985): Hospital-acquired (nosocomial) infections kill ~99,000 people per year in the US alone. The single most effective intervention is healthcare worker hand hygiene, which was understood since Semmelweis (1847) yet remained chronically under-practiced. Didier Pittet's alcohol-based handrub and the WHO "Five Moments" standardized modern infection control.
- HIV Screening of the Blood Supply (Optimal Year: 1983): Before HIV screening of donated blood, the US blood supply was contaminated. ~12,000 Americans (mostly hemophiliacs and transfusion recipients) became infected with HIV through blood products between 1978 and 1985. The HIV antibody ELISA test (licensed March 1985) ended this. Heat treatment of clotting factors (1984) protected hemophiliacs sooner.
- Sterile Technique & Surgical Safety Checklist (Optimal Year: 1980): Standardized sterile technique, instrument counts, time-outs, and the WHO Surgical Safety Checklist cut surgical morbidity and mortality by 30-40%. The 19-step checklist was proven by Haynes et al. (NEJM 2009) but the principles are timeless and could have been standardized decades earlier.
`;
