export const era_1990__science__medical = `
## 1990S SCIENCE - MEDICAL
- Triple-Drug HIV Therapy (HAART) (Optimal Year: 1995): Highly Active Antiretroviral Therapy (HAART) combines three drugs (like protease inhibitors with RT inhibitors) to suppress HIV replication, preventing AIDS and resistance.
- Somatotype Somatic Cell Nuclear Transfer (SCNT) (Optimal Year: 1996): Cloning mammals using somatic cells (adult body cells) rather than embryonic cells. Replaces the dogma that adult cells are irreversibly differentiated.
- Human Genome Project Acceleration (Optimal Year: 1990): Mapping and sequencing the entire human genome. The draft sequence was published in 2001; the complete sequence in 2003.
- Folic Acid Fortification to Prevent Neural Tube Defects (Optimal Year: 1990): Periconceptional folic acid supplementation reduces neural tube defects (spina bifida, anencephaly) by ~70%. The MRC Vitamin Study (1991) was the definitive proof. Food fortification (mandatory US 1998) prevents ~1,300 NTD-affected pregnancies per year in the US alone.
- DOTS Strategy for Tuberculosis Treatment (Optimal Year: 1991): Tuberculosis kills ~1.5 million people per year and was resurgent in the 1990s (HIV co-epidemic, drug resistance). The WHO's DOTS strategy (Directly Observed Treatment, Short-course) standardized the 6-month multi-drug regimen with direct observation of pill-taking to ensure adherence, preventing relapse and drug resistance.
- Magnesium Sulfate for Eclampsia & Pre-Eclampsia (Optimal Year: 1990): Magnesium sulfate halves the risk of eclamptic seizures in women with pre-eclampsia and is more effective than diazepam or phenytoin for treating eclampsia itself. Eclampsia is a leading cause of maternal death worldwide. Yet magnesium sulfate was controversially underused for decades, especially outside the US.
- Antenatal Corticosteroids for Preterm Birth (Fetal Lung Maturation) (Optimal Year: 1990): Antenatal corticosteroids (betamethasone or dexamethasone) given to a woman at risk of preterm delivery accelerate fetal lung maturation, reducing neonatal respiratory distress syndrome by ~50% and neonatal mortality by ~30%. The effect was discovered by Graham Liggins in 1969 and proven by the landmark Liggins & Howie RCT in 1972.
`;
