export const era_1990__economics__finance = `
## 1990S ECONOMICS - FINANCE
- 1995-08-09 (IPO): Netscape IPO — Dot-com Boom Catalyst. Direction: UP. Peak: Stock: $28 → $75 on first day  This IPO marks the official birth of the Dot-com bubble. Opens at $71 after pricing at $28, valuing a 16-month-old company at $3B.
- 1997-05-15 (IPO): Amazon.com IPO. Direction: UP. Peak: Stock: $18 (split-adjusted $0.075) → $170+ by 2024  Amazon goes public as a simple online bookstore. Survive the dot-com crash to capture a trillion-dollar cloud and e-commerce giant.
- 1997-07-02 (Market Crash): Asian Financial Crisis. Direction: DOWN. Peak: Baht: 25/USD → 56/USD by Jan 1998  Tigers of Southeast Asia suffer massive flight of hot money. Begins with Thai Baht collapse and cascades to Korea, Indonesia, and Hong Kong.
- 1990-08-02 to 1990-10-11 (Commodity): Gulf War Oil Spike. Direction: UP. Peak: Oil: $15 → $40/barrel (Oct 11, 1990) Trough: Oil back below $20 by Feb 1991 Spike is sharp but short. Oil back below $20 by Feb 1991 as the ground war proves quick. This oil shock directly causes the 1990-91 US recession.
- 1990-01-12 (Market Crash): Japanese Asset Bubble Bursts. Direction: DOWN. Peak: Nikkei: 30,000+ → 20,000 in 3 months Trough: Oct 1990: Nikkei near 20,000 The first 3 months of 1990 erase 40% of Japanese stock market wealth. Land values follow stocks down over the next decade. "The Lost Decade(s)" begin.
- 1990-02-16 (IPO): Cisco Systems IPO. Direction: UP. Peak: IPO: $18/share (split-adjusted ~$0.04) Trough: Brief 1990 dip below IPO Stanford spin-out by Len Bosack and Sandy Lerner. By 2000 Cisco is the backbone of the internet. The quintessential infrastructure play of the internet build-out.
- 1992-06-26 (IPO): Starbucks IPO. Direction: UP. Peak: IPO: $17/share (split-adjusted ~$0.27) Trough: 1993 dip: low single digits pre-split Howard Schultz's espresso bar vision scales nationally. 165 stores at IPO, 38,000+ today. The defining "third place" brand of the era.
- 1992-09-16 (Currency): Black Wednesday — Soros Breaks the Bank of England. Direction: DOWN. Peak: GBP/DM: 2.95 → 2.70 in hours Trough: GBP falls ~15% over the following weeks Soros's Quantum Fund books ~$1B profit. The Bank of England spends ~£3B defending the peg before capitulating. UK European monetary credibility is permanently damaged.
- 1994-12-20 (Currency): Mexican Peso Crisis (Tequila Crisis). Direction: DOWN. Peak: MXN: 3.4/USD → 7.2/USD by Mar 1995 Trough: Peso bottoms near 7.2 in Q1 1995 Zedillo's Dec 20, 1994 devaluation announcement triggers a "Tequila effect" across emerging markets. Clinton's $50B bailout (using the Exchange Stabilization Fund) is highly controversial.
- 1998-08-17 (Market Crash): Russian Debt Default. Direction: DOWN. Peak: Russian GKO yields spike to 200%+ Trough: Ruble devalues from 6 to 21/USD by year-end Russia defaults on ~$40B of domestic GKO debt. The shock cascades through leveraged hedge funds and directly triggers the LTCM crisis weeks later.
- 1998-09-23 (Market Crash): Long-Term Capital Management Collapse. Direction: DOWN. Peak: Credit spreads blow out: Baa-Aaa 200bp → 250bp Trough: LTCM equity wiped out (-90% YTD by Sept LTCM has two Nobel laureates (Scholes, Merton) and 25:1 leverage. The Fed-orchestrated bailout prevents a systemic meltdown and reshapes risk management for decades.
- 1999-07-20 to 1999-08-25 (Commodity): Gold Bottoms at $253/oz. Direction: UP. Peak: Gold: $253 → $1,900+ by Sept 2011 Trough: Intraday low $252.80 (July 20, 1999) UK Chancellor Gordon Brown sells 50% of UK gold reserves at the absolute bottom (~$275 average). Gold returns ~7.5x by 2011. The peak of "gold is dead" consensus sentiment.
- 1999-01-04 (Currency): Euro Launch. Direction: DOWN. Peak: EUR/USD: 1.18 (Jan 4, 1999) Trough: EUR/USD: 0.8230 all-time low (Oct 26, 2000) The euro debuts with sky-high expectations and immediately disappoints. Most analysts predict parity and above — they are wrong for nearly 2 years.
- 1999-01 to 2000-03-10 (IPO): Dot-com Mania — Final Parabolic Phase. Direction: UP. Peak: NASDAQ: 2,200 → 5,048 (+130%) Trough: Day-1 IPO pops average ~65% 1999 alone sees ~470 internet IPOs. The average first-day pop is ~65%. Many "dot-com" companies have no revenue and never will. Mania of historic proportions.
- 1999-12-31 to 2000-01-03 (Market Crash): Y2K Bug — The Non-Event. Direction: UP. Peak: Y2K remediation stocks peak into year-end Trough: IT-services stocks collapse Jan 2000 Estimates of global Y2K remediation spending: $300B+. Almost nothing fails at midnight. The sell-in-January-2000 trade in IT services is a well-known seasonal anomaly.
`;
