export const era_2000__culture__sports = `
## 2000S CULTURE - SPORTS
- World Series 2001 (2001): Arizona Diamondbacks def. New York Yankees 4-3 (Yankees slight favorites), First World Series after 9/11. D-backs score 2 runs in bottom of 9th in Game 7 off Mariano Rivera, Luis Gonzalez hits walk-off single.
- World Series — "Subway Series" (2000): New York Yankees def. New York Mets 4-1 (Yankees -160), First Subway Series since 1956. Yankees win their 3rd straight World Series (4th in 5 years). Roger Clemens throws a broken bat shard at Mike Piazza. Derek Jeter hits .400 and wins MVP.
- Super Bowl XXXVI (2002): New England Patriots def. St. Louis Rams 20-17 (Rams -14), Played in Feb 2002 for 2001 season. First Super Bowl won on final play. Adam Vinatieri 48-yd GW FG. Tom Brady wins MVP.
- Super Bowl XXXIV (2000): St. Louis Rams def. Tennessee Titans 23-16 (Rams -7), "The Tackle" — Mike Jones stops Kevin Dyson at the 1-yard-line on the final play of the game. Kurt Warner goes from grocery stock boy to Super Bowl MVP (414 yds, 2 TDs). "The Greatest Show on Turf."
- World Series 2001 (2001): Arizona Diamondbacks def. New York Yankees 4-3 (Yankees slight favorites), First World Series after 9/11. D-backs score 2 runs in bottom of 9th in Game 7 off Mariano Rivera, Luis Gonzalez hits walk-off single.
- Summer Olympics — Sydney 2000 (2000): United States (37 gold) def. Russia (32 gold) USA top table, Widely hailed as the best-organized Games ever. Cathy Freeman lit the cauldron and won 400m gold in a full-body suit before 112,000 home fans. Ian "Thorpedo" Thorpe won 3 golds at 17. Marion Jones won 5 golds (all later stripped for doping). The first Games held in spring in the Southern Hemisphere.
- F1 World Championship — 2000 (2000): Michael Schumacher def. Mika Häkkinen 108 vs 89 pts, Schumacher ends Ferrari's 21-year drivers' title drought — the longest in their history. Won the last 4 races after trailing Häkkinen mid-season. The emotion at Monza, post-win, was palpable. The start of Ferrari's 5-year dynasty.
- F1 World Championship — 2001 (2001): Michael Schumacher def. David Coulthard 123 vs 62 pts, Schumacher's 4th title, clinched with 4 races to spare — the earliest ever at the time. Won 9 races and stood on the podium in all 17. His brother Ralf won 3 races for Williams-BMW. The most dominant season of the Schumacher-Ferrari era.
- Wimbledon Men's Singles — 2000 (2000): Pete Sampras def. Pat Rafter 6-7, 7-6, 6-4, 6-2, Sampras wins his 7th Wimbledon, breaking Emerson's record with 13 Grand Slams. His 4th straight Wimbledon title. Played through tendinitis in his foot and hip. The high point of "Pistol Pete's" career.
- Wimbledon Men's Singles — 2001 (2001): Goran Ivanišević def. Pat Rafter 6-3, 3-6, 6-3, 2-6, 9-7, Ivanišević becomes the first wildcard to win a Grand Slam and the first to win on a Monday after rain delays. A 3-time runner-up finally breaks through. An emotional, against-all-odds victory by one of tennis's most beloved characters.
- Wimbledon Women's Singles — 2000 (2000): Venus Williams def. Lindsay Davenport 6-3, 7-6, Venus Williams wins her first Grand Slam at age 20. The power game she and her sister Serena pioneered would transform women's tennis. The first all-power era champion.
- Wimbledon Women's Singles — 2001 (2001): Venus Williams def. Justine Henin 6-1, 3-6, 6-0, Venus defends her Wimbledon title. A bagel in the final set of a Wimbledon final was remarkable. Venus became the first woman since Graf to defend Wimbledon.
- US Open Women's Singles — 2001 (2001): Venus Williams def. Serena Williams 6-2, 6-4, The first all-sister US Open final since 1884. Venus defeats Serena in straight sets. The Williams sisters' dominance of women's tennis had begun in earnest — they would meet in 9 Grand Slam finals.
- Australian Open Men's Singles — 2001 (2001): Andre Agassi def. Arnaud Clément 6-4, 6-2, 6-2, Agassi wins his 3rd Australian Open. Did not drop a set in the final. Agassi would go on to win 4 Australian Opens — his most successful Slam. The dominant champion of the early-2000s hard courts.
`;
