export const era_global__science__blueprints = `
## GLOBAL SCIENCE - BLUEPRINTS
- Silicon Crystal Pulling (Czochralski Method): Process to pull a high-purity mono-crystalline silicon ingot from a molten pool of purified metallurgical-grade silicon, forming the basis of all silicon wafers. Key materials: Refined polycrystalline silicon (99.9999999% purity), Quartz (SiO2) crucible, High-purity graphite susceptor, Argon gas supply (99.999% purity), Single-crystal seed (typically [100] or [111] orientation), Radio-frequency (RF) induction heating coils.
- Optical Reduction Photolithography (Step-and-Repeat): Projecting micro-circuit patterns from a master reticle (mask) onto a photoresist-coated wafer at a reduced scale (typically 10:1 or 5:1) using ultraviolet light. Key materials: High-pressure Mercury Arc Lamp, Highly corrected multi-element quartz lens system, Novolac-based positive photoresist, Tetramethylammonium hydroxide (TMAH) developer, Chromium-coated quartz glass mask plates, Hexamethyldisilazane (HMDS) adhesion promoter.
- Precision Ball Screws & Closed-Loop CNC Control: Mechanical drive systems using recirculating ball bearings to convert rotary motor shaft rotation to sub-micron linear motion with near-zero backlash, coupled with optical linear encoder feedback. Key materials: High-grade carbon alloy steel (AISI 4150 or similar), Precision-ground chrome steel balls (Grade 10 or better), Double ball-nut housing with adjustable shim spacing, Fine glass scale grating (e.g. 100 lines/mm), LED light source and photodiode detection array, DC permanent magnet servo motors, High-precision Grade AA granite surface plates.
- Silicon Planar Process (Hoerni Planar Transistor): Jean Hoerni's breakthrough process to manufacture flat transistors protected by a passivating silicon dioxide layer, enabling monolithic integrated circuits. Key materials: Purified silicon wafer slices (P-type, doped with Boron), Deionized water and high-purity Oxygen gas, Buffered Hydrofluoric acid (HF) etchant solution, Phosphorus oxychloride (POCl3, N-type dopant source), Boron tribromide (BBr3, P-type dopant source), Pure Aluminum charge and vacuum deposition crucible.
- Electromagnetic Telegraph (Morse Single-Wire System): Samuel Morse's single-wire electromagnetic telegraph: a battery, a hand-operated make/break "key" at the sending end, an electromagnet and "sounder" at the receiving end, and Earth itself as the return conductor. Pulses encode letters in Morse code. Key materials: Insulated copper line wire (~14 AWG, gutta-percha or tar-impregnated cotton insulation), Soft iron bar stock for electromagnet cores (horseshoe shape), Magnet wire for coil windings (silk- or cotton-insulated, ~18 AWG), Zinc-carbon wet Leclanché cells (porous pot, manganese dioxide depolarizer), Hardwood mounting blocks, brass hardware, spring steel for armatures, Copper-clad ground rods (driven into moist soil), Tinplate lightning arresters with adjustable spark gap.
- Daguerreotype Photographic Process: Louis Daguerre's process for capturing a permanent direct-positive image on a silver-plated copper sheet sensitized with silver iodide, developed by exposure to mercury vapor, and fixed with sodium thiosulfate ("hypo"). One-of-a-kind image; exposure times start at ~10 minutes and drop toward 30 seconds by the 1840s with lens and chemistry improvements. Key materials: Rolled copper sheet (~1.6 mm thick), 8×10 cm or larger, Fine silver (99.9%) for electroplating — approx. 3 g per plate, Iodine crystals (sublimed) for fuming box sensitization, Bromine optional, for faster "accelerator" plates from 1840 onward, Mercury (≈2 kg per fuming trough; highly toxic — fume hood required), Sodium thiosulfate ("hypo") for fixing, Distilled water, sodium carbonate, nitric acid for cleaning, Cork and velvet buffing wheels for final plate polishing, Wollaston-style landscape lens (early); Chevalier achromat (post-1841).
- Monier Reinforced Concrete (Iron-Mesh Composite): Joseph Monier's composite of Portland cement concrete reinforced with an inner cage of iron rods or wire mesh. The concrete carries compressive load; the iron carries tensile load. Together they form a slab, beam, or pipe far stronger than either material alone. Key materials: Portland cement (≈1 part by volume; rotary-kiln grade after 1885), Clean sharp sand (≈2 parts; graded 0–4 mm), Crushed stone or gravel aggregate (≈4 parts; graded 4–20 mm), Clean water (≈0.5 parts; potable, low chloride), Wrought iron or mild steel bars, ~10–20 mm diameter, Iron-wire mesh or expanded metal lath for thin slabs, Wooden formwork (planks, stakes, ties), oiled to release, Tampers, screed boards, and a curing pond or wet burlap.
- Single-Cylinder Four-Stroke Gasoline Engine (Benz Patent-Motorwagen): Karl Benz's 954 cc single-cylinder four-stroke gasoline engine running at ~400 rpm, output ~0.75 hp. Each cylinder is cast iron with a water jacket; a surface carburetor vaporizes fuel; ignition is by hot-tube or low-voltage trembler coil; cooling is thermosiphon via a radiator. Key materials: Cast iron for cylinder block, piston, and crankcase, Forged steel crankshaft, connecting rod, and flywheel shaft, Mild steel or brass water jacket around cylinder, Wrought-iron or copper fuel and water piping, Surface carburetor (brass float bowl, calibrated jet, throttle butterfly), Hot-tube ignition: porcelain tube with platinum wire coil, Bunsen burner, Lead-acid or zinc-carbon primary battery for coil (trembler) ignition, Linen or leather drive belt; roller chain for final drive, Pattern wood for sand casting the cylinder block and piston.
`;
