export const era_global__events__safety = `
## GLOBAL EVENTS - SAFETY
- Paper Identity Documents (Identity): 1970s driver's licenses and Social Security cards are paper-based with minimal security features. This is a window of opportunity.
- Cover Story Construction (Identity): Your backstory must be verifiable AND unremarkable. Nobody investigates the unremarkable.
- Cash-Based Existence (Banking): In the 1970s, cash is normal. Many people don't have bank accounts. Operating in cash is not suspicious.
- Converting Foreknowledge to Wealth (Quietly) (Banking): Making money is easy with a sports almanac. Keeping it without attracting attention is the hard part.
- Finding Housing Without History (Housing): Pre-credit-check era means housing is easier to obtain than in modern times — if you know the rules.
- Vaccination & Biological Risk (Medical): You carry antibodies to diseases that don't exist yet. This makes you neither a vector nor vulnerable — but take precautions.
- Medication & Treatment Awareness (Medical): Many modern medications don't exist yet. Know what you can and can't access.
- Newspaper Classified Ads (Dead Drops): The most reliable dead-drop method of the era. Millions of people read classifieds daily. Coded messages are invisible among the noise.
- Safety Deposit Boxes (Dead Drops): Open a box in one year, retrieve the contents in another. The longest-duration dead drop that requires no maintenance.
- Library Book Annotations (Dead Drops): Marginalia in specific editions at specific libraries. Low-tech, durable, and accessible without ID.
- Physical Dead Drops (Geocaching, 1970s Style) (Dead Drops): Bury or hide a waterproof container at pre-arranged GPS coordinates — except you don't have GPS. You need detailed physical descriptions.
- Book Cipher for Temporal Communication (Dead Drops): You need a cipher that works with era-appropriate tools (no computers for the 1970s version of you).
- Analog Cellphone Sniffing & Cloning (Communication): 1990s cellphones (AMPS analog standard) transmit electronic serial numbers (ESN) and mobile identification numbers (MIN) in the clear. Criminals intercept and clone them.
- Pager / Beeper Numeric Cryptography (Communication): Pagers are the default mobile communication tool in the 90s. Messages are often public and unencrypted.
- Flexibility Protocol — When History Doesn't Match the Records (Identity): The further back you travel, the more likely the historical record is incomplete, distorted, or simply wrong. Written accounts are often propaganda, survivor bias, or later reconstruction. You need a playbook for when things are different from what you expect.
- Early Internet Security & Email Scams (Communication): The 1990s internet has minimal security. Plaintext email, no HTTPS by default, and trust-based chatrooms create exposure vectors.
- PGP & Public Key Cryptography (Communication): Philip Zimmermann releases Pretty Good Privacy (PGP) v1.0 in June 1991. By mid-90s, RSA keys offer real confidentiality for email — and the US government opens a criminal investigation for "munitions export without a license."
- Pre-Firewall Computer Hygiene (Communication): Internet-connected hosts in the early 90s are wide open. Default installs of Windows, Mac, and Linux ship with telnet, FTP, and unpatched services. Firewalls are rare until 1994-95.
- Ham Radio — The Only Decentralized Network (Communication): Amateur ("ham") radio works when phones, internet, and the power grid all fail. It spans the globe on shortwave with zero infrastructure. A US Technician-class license requires a simple written test (Morse code required until 2000).
- Phone Phreaking & Blue Box Era Notes (Communication): From the 1950s to mid-80s, the Bell System's in-band signaling (2600 Hz MF tones) lets anyone with a "blue box" route free long-distance calls. By the 90s, common-channel signaling (SS7) makes blue boxes obsolete — but the culture persists.
- Map & Compass Navigation (Pre-GPS) (Communication): GPS is military-only until the 1983 KAL 007 shootdown prompts Reagan to make it partially civilian. Selective Availability degrades civilian GPS accuracy until May 2000. For most of the era, navigation is map, compass, and dead reckoning.
- Celestial Navigation Fundamentals (Communication): For ocean crossings or wilderness travel, the night sky is a reliable clock and compass. Polaris gives latitude directly in the Northern Hemisphere; a sextant plus a nautical almanac gives longitude.
- Public Transit Systems By City (Communication): Cars leave paper trails: registration, license plate, insurance, toll records. Public transit — especially cash-paid subway and bus — is one of the most anonymous ways to move in any era.
- Emergency Contact & Dead-Man Protocols (Communication): A scheduled check-in with a designated contact is your canary. Missing a check-in by more than X hours triggers a contingency script — even if you cannot explain your situation to a 1970s police officer.
- Era-Appropriate Emergency Medical Kit (Medical): Modern trauma kits (CAT tourniquets, hemostatic gauze, naloxone) are not yet standard. Build your own from era-available components.
- First Aid Procedures (Era-Specific Risks) (Medical): Common 1970s-90s hazards differ from modern ones: more industrial accidents, smoking-related burns, fewer seatbelt laws (federal mandate 1984, state laws spread through the 90s).
- Building A Prescription Stockpile (Medical): Many essential medications (insulin, antibiotics, thyroid, cardiac) are needed continuously. The modern insurance/pharmacy system is unforgiving of gaps. Build a buffer.
- Situational Awareness & The Cooper Color Code (Identity): Self-defense begins long before any physical confrontation. Jeff Cooper's "Color Code" (1970s, popularized in "Principles of Personal Defense") is the era-appropriate framework: White (unaware) → Yellow (relaxed alert) → Orange (focused alert) → Red (action).
- Improvised & Legal Self-Defense Tools (Identity): Gun laws vary wildly by state and era. Pepper spray (mace) is legal most places from 1965. Many everyday objects double as effective defensive tools.
- Rapid Language Acquisition Strategies (Identity): Fitting into a non-English environment requires functional fluency in weeks, not years. Pre-internet tools (Pimsleur, Berlitz, Foreign Service Institute tapes) are your best accelerators.
- Accent Management & Neutralization (Identity): An accent is the single hardest part of identity to change. Native listeners detect micro-deviations even when vocabulary and grammar are perfect.
- Era-Specific Cultural Norms (Identity): Social etiquette changes faster than people realize. Behaviors that are normal in 2025 are rude or bizarre in 1980, and vice versa. Failure to assimilate marks you instantly.
- Avoiding Anachronistic Behavior (Identity): The single biggest giveaway that you are from the future. Behaviors, vocabulary, and references that are 5+ years out of sync with the era will mark you instantly.
- Era Fashion Adaptation (Identity): Clothing is the fastest visual signal you send. Wearing 2025 fashion in 1975 is impossible to hide. Buy local, current clothes immediately upon arrival.
- Financial Diversification Across Decades (Banking): A single bank, broker, or currency is a single point of failure. Time travelers face unique risks: institution collapse, identity exposure, currency redenomination, and the possibility that "your" records do not survive your interventions.
`;
